/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.boxalino.p13n.api.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * list of personalized variants. Item's index corresponds to the index of the
 * ChoiceInquiry
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-01-25")
public class ChoiceResponse implements org.apache.thrift.TBase<ChoiceResponse, ChoiceResponse._Fields>, java.io.Serializable, Cloneable, Comparable<ChoiceResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ChoiceResponse");

  private static final org.apache.thrift.protocol.TField VARIANTS_FIELD_DESC = new org.apache.thrift.protocol.TField("variants", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ChoiceResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ChoiceResponseTupleSchemeFactory();

  public java.util.List<Variant> variants; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VARIANTS((short)1, "variants");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VARIANTS
          return VARIANTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VARIANTS, new org.apache.thrift.meta_data.FieldMetaData("variants", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Variant.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ChoiceResponse.class, metaDataMap);
  }

  public ChoiceResponse() {
  }

  public ChoiceResponse(
    java.util.List<Variant> variants)
  {
    this();
    this.variants = variants;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ChoiceResponse(ChoiceResponse other) {
    if (other.isSetVariants()) {
      java.util.List<Variant> __this__variants = new java.util.ArrayList<Variant>(other.variants.size());
      for (Variant other_element : other.variants) {
        __this__variants.add(new Variant(other_element));
      }
      this.variants = __this__variants;
    }
  }

  public ChoiceResponse deepCopy() {
    return new ChoiceResponse(this);
  }

  @Override
  public void clear() {
    this.variants = null;
  }

  public int getVariantsSize() {
    return (this.variants == null) ? 0 : this.variants.size();
  }

  public java.util.Iterator<Variant> getVariantsIterator() {
    return (this.variants == null) ? null : this.variants.iterator();
  }

  public void addToVariants(Variant elem) {
    if (this.variants == null) {
      this.variants = new java.util.ArrayList<Variant>();
    }
    this.variants.add(elem);
  }

  public java.util.List<Variant> getVariants() {
    return this.variants;
  }

  public ChoiceResponse setVariants(java.util.List<Variant> variants) {
    this.variants = variants;
    return this;
  }

  public void unsetVariants() {
    this.variants = null;
  }

  /** Returns true if field variants is set (has been assigned a value) and false otherwise */
  public boolean isSetVariants() {
    return this.variants != null;
  }

  public void setVariantsIsSet(boolean value) {
    if (!value) {
      this.variants = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case VARIANTS:
      if (value == null) {
        unsetVariants();
      } else {
        setVariants((java.util.List<Variant>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case VARIANTS:
      return getVariants();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case VARIANTS:
      return isSetVariants();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ChoiceResponse)
      return this.equals((ChoiceResponse)that);
    return false;
  }

  public boolean equals(ChoiceResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_variants = true && this.isSetVariants();
    boolean that_present_variants = true && that.isSetVariants();
    if (this_present_variants || that_present_variants) {
      if (!(this_present_variants && that_present_variants))
        return false;
      if (!this.variants.equals(that.variants))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetVariants()) ? 131071 : 524287);
    if (isSetVariants())
      hashCode = hashCode * 8191 + variants.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ChoiceResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetVariants()).compareTo(other.isSetVariants());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVariants()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.variants, other.variants);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ChoiceResponse(");
    boolean first = true;

    sb.append("variants:");
    if (this.variants == null) {
      sb.append("null");
    } else {
      sb.append(this.variants);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ChoiceResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ChoiceResponseStandardScheme getScheme() {
      return new ChoiceResponseStandardScheme();
    }
  }

  private static class ChoiceResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<ChoiceResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ChoiceResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VARIANTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list226 = iprot.readListBegin();
                struct.variants = new java.util.ArrayList<Variant>(_list226.size);
                Variant _elem227;
                for (int _i228 = 0; _i228 < _list226.size; ++_i228)
                {
                  _elem227 = new Variant();
                  _elem227.read(iprot);
                  struct.variants.add(_elem227);
                }
                iprot.readListEnd();
              }
              struct.setVariantsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ChoiceResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.variants != null) {
        oprot.writeFieldBegin(VARIANTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.variants.size()));
          for (Variant _iter229 : struct.variants)
          {
            _iter229.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ChoiceResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ChoiceResponseTupleScheme getScheme() {
      return new ChoiceResponseTupleScheme();
    }
  }

  private static class ChoiceResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<ChoiceResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ChoiceResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetVariants()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetVariants()) {
        {
          oprot.writeI32(struct.variants.size());
          for (Variant _iter230 : struct.variants)
          {
            _iter230.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ChoiceResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list231 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.variants = new java.util.ArrayList<Variant>(_list231.size);
          Variant _elem232;
          for (int _i233 = 0; _i233 < _list231.size; ++_i233)
          {
            _elem232 = new Variant();
            _elem232.read(iprot);
            struct.variants.add(_elem232);
          }
        }
        struct.setVariantsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

